export const currentReportStore = {
  moneySums: {},
  moneyCodes: [],
  date: "",
  route: undefined,
  hike: undefined,
  members: "",
  inactiveMembers: "",
  paymentsFromInstructors: [],
  paymentsFromTutors: [],
  paymentsFromMembers: [],
  paymentsFromOffice: [],
  expenses: [],
  conversions: [],
  paymentsToInstructors: [],
  paymentsToTutors: [],
  paymentsToOffice: [],
  instructorsRevenue: [],
};
